# CONFIGURATION
zaug_lambda: 10.0

# Model Parameters
state_dim: 2
action_dim: 2
latent_dim: 1
hidden_dim: 10

# Optimization Parameters --> Batch Size, Learning Rate, Step Size (Number of Steps before decay), Gamma (Decay Rate)
bsz: 1024
lr: 0.01
lr_step_size: 200
lr_gamma: 0.1

# Training Parameters
epochs: 700
gpus: 0

# Augmentation Parameters
augment: True
augmentation_factor: 1
augment_factor: 1

# Run Parameters
experiment_name: '2d_nav_latent_prefs_acqr'
uncertainty_context: 'latent_prefs'
task_domain: '2d_nav'

# Demonstration Directory
demo_data_dir: 'trial_data_calib_noise'


# Calibration type, and parameters
calibration_type: 'acqr' # acqr, qr, or ensemble
acqr_gamma: 0.005
desired_alpha: 0.1



















