# CONFIGURATION
zaug_lambda: 10.0

# Model Parameters
state_dim: 7
action_dim: 7
latent_dim: 2
hidden_dim: 30

# Optimization Parameters --> Batch Size, Learning Rate, Step Size (Number of Steps before decay), Gamma (Decay Rate)
bsz: 4064
lr: 0.01
lr_step_size: 200
lr_gamma: 0.1

# Training Parameters
epochs: 20
gpus: 0

# Augmentation Parameters
augment: True
augmentation_factor: 1
augment_factor: 1

# Run Parameters
experiment_name: '7dof_cup_latent_prefs_acqr'
uncertainty_context: 'latent_prefs'
task_domain: '7dof_cup_grasping'

# Demonstration Directory
demo_data_dir: 'trial_data_complex_pouring_task'


# Calibration type, and parameters
calibration_type: 'acqr' # acqr, qr, or ensemble
acqr_gamma: 0.005
desired_alpha: 0.1



















